repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: flake8
