language: python

dist: xenial

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run black --check .
  - pipenv run isort --recursive --check-only --diff
  - pipenv run flake8
