version: '3'

volumes:
  database:
    external: false

  redis:
    external: false

services:
  database:
    image: postgres:10.6
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: start-worker
    entrypoint: /app/bin/docker-entrypoint
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - database:database
      - redis:redis

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: start-web
    entrypoint: /app/bin/docker-entrypoint
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    links:
      - database:database
      - redis:redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/readiness/"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: start-test
    entrypoint: /app/bin/docker-entrypoint
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    links:
      - database:database
      - redis:redis