# Generated by Django 3.1.3 on 2020-12-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20181006_1531")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        )
    ]
