# Generated by Django 2.1.2 on 2018-10-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=255)),
                ('amendment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_grant', models.DateTimeField()),
                ('effective_date_from', models.DateTimeField()),
                ('effective_date_to', models.DateTimeField()),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('has_amendments', models.BooleanField()),
                ('exempt_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_id', models.PositiveIntegerField()),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('source_url', models.URLField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractors',
            field=models.ManyToManyField(to='contracts.Contractor'),
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.Document'),
        ),
        migrations.AddField(
            model_name='contract',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.Entity'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.Service'),
        ),
    ]
