# Generated by Django 2.1.3 on 2018-12-03 15:42

import contratospr.contracts.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contracts", "0002_auto_20181118_1525")]

    operations = [
        migrations.AlterModelOptions(name="contractor", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(
            name="entity",
            options={"ordering": ["name"], "verbose_name_plural": "Entities"},
        ),
        migrations.AlterModelOptions(name="service", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(
            name="servicegroup", options={"ordering": ["name"]}
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=contratospr.contracts.models.document_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="preview_data_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=contratospr.contracts.models.document_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="vision_data_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=contratospr.contracts.models.document_file_path,
            ),
        ),
    ]
