# Generated by Django 2.2.4 on 2019-08-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("contracts", "0004_auto_20190102_2147")]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amendments",
                to="contracts.Contract",
            ),
        )
    ]
