# Generated by Django 3.1.3 on 2020-12-12 21:29

import contratospr.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("contracts", "0005_auto_20190825_1958"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    contratospr.utils.fields.DateTimeCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified_at",
                    contratospr.utils.fields.DateTimeModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("date_of_grant_start", models.DateField()),
                ("date_of_grant_end", models.DateField()),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.RemoveField(model_name="document", name="preview_data_file"),
        migrations.RemoveField(model_name="document", name="vision_data_file"),
        migrations.AlterField(
            model_name="document",
            name="pages",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CollectionArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    contratospr.utils.fields.DateTimeCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified_at",
                    contratospr.utils.fields.DateTimeModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("serialized_data", models.TextField()),
                ("object_repr", models.TextField()),
                ("created", models.BooleanField()),
                (
                    "collection_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="contracts.collectionjob",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
    ]
