# Generated by Django 2.1.3 on 2018-11-13 16:41

import contratospr.contracts.models
from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_document_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='preview_data',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vision_data',
        ),
        migrations.AddField(
            model_name='document',
            name='preview_data_file',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to=contratospr.contracts.models.document_file_path),
        ),
        migrations.AddField(
            model_name='document',
            name='vision_data_file',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to=contratospr.contracts.models.document_file_path),
        ),
    ]
