# Generated by Django 3.1.12 on 2021-09-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contracts", "0006_auto_20201212_2129")]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="source_id",
            field=models.CharField(max_length=255, unique=True),
        )
    ]
