name: Build and test ContratosPR API

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit checks
      run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Test with pytest
        run: pipenv run python runtests.py --nolint
        env:
          DATABASE_URL: ${{ format('postgres://postgres:postgres@localhost:{0}/postgres', job.services.postgres.ports[5432]) }}
